config/routes.rb
Rails.application.routes.draw do
  root 'awards#index'
  resources :awards

  get '*path' => redirect('/')
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :set_award, only: [:show, :edit, :update, :destroy]

  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.all
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
  end

  # GET /awards/new
  def new
    @award = Award.new
  end

  # GET /awards/1/edit
  def edit
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(award_params)

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @award }
      else
        format.html { render :new }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      else
        format.html { render :edit }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award.destroy
    respond_to do |format|
      format.html { redirect_to awards_url, notice: 'Award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_award
      @award = Award.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def award_params
      params.require(:award).permit(:name, :description, :nomination_close_date, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.erb
<%= form_with(model: award, local: true) do |form| %>
  <% if award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field row">
      <%= form.label :name, class: "col-form-label col-sm-3 col-md-2" %>
      <div class="col-sm-9 col-lg-8">
      <%= form.text_field :name, id: :award_name, class: 'form-control ', placeholder: "Name of the award" %>
      </div>
  </div>

  <div class="form-group field row">
    <%=  form.label :link, class: "col-form-label col-sm-3 col-md-2" %>
    <div class="col-sm-9 col-lg-8">
    <%=  form.text_field :link, id: :award_link, class: 'form-control', placeholder: "URL to find more information or apply" %>
  </div>
  </div>

  <div class="form-group field row">
    <%= form.label :description, class: "col-form-label col-sm-3 col-md-2" %>
    <div class="col-sm-9 col-lg-8">
    <%= form.text_area :description, id: :award_description, class: 'form-control', rows: "10", placeholder: "A brief description of the award. Who is eligible? What are the selection criteria?" %>
    </div>
  </div>

  <div class="form-group field row">
    <%= form.label :nomination_close_date, class: "col-form-label col-sm-3 col-md-2" %>
    <div class="col-sm-9 col-lg-8">
    <%= form.date_field :nomination_close_date, id: :award_nomination_close_date, format: :short, class: 'form-control', placeholder: "MM/DD/YYYY" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn-primary btn-lg' %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<div class="header">
    <div class="container">
        <%= link_to 'Nominate Her', awards_path %>
    </div>
</div>

<div class="page-title">
	<div class="container">
	    <h1>Edit award</h1>
    </div>
</div>

<div class="container">
<%= render 'form', award: @award %>

</div>

app/views/awards/index.html.erb
<p id="notice"><%= notice %></p>

<div class="hero container-fluid">
    <div class="row">
        <div class="col-12">
            <h1>Nominate Her:</h1>
            <h2>A collaborative listing of awards for women in tech</h2>
        </div>
    </div>
    <div class="row pt-5 pb-3">
        <div class="col-sm-6 col-md-8 pr-5">
            <p class="lead"> This site was started by Jessica Garson who, after winning an award, wanted more women to experience that feeling. The project was later developed further at the 2017 <a href="https://techladyhackathon.org/">Tech Lady Hackathon</a> in Washington, DC.</p>
        </div>
        <div class="col-sm-6 col-md-4">
            <p class="h5 mb-3 mt-1"><strong>Help make this list more complete!</strong></p>
<!--             <p>If you know of an award not listed here, let us know.</p>
            <p> -->
            <a class="btn btn-primary" href=<%= new_award_path %>>Add an Award</a>
            </p>
        </div>
    </div>
</div>


<section class="card-holder-awards">
    <div class="card-grid">
        <% @awards.each do |award| %>
            <div class="card">
                <div class="card-body">
                    <h2><a href="<%= award.link %>" target="blank"><%= award.name %></a></h2>
                    <p><%= award.description %></p>
                    <p><span class="deadline">Application deadline</span> <%= award.nomination_close_date %></p>
                </div>
                <div class="card-footer">
                    <ul class="list-inline">
                        <li class="list-inline-item"><%= link_to 'Show', award %></li>
                        <li class="list-inline-item"><%= link_to 'Edit', edit_award_path(award) %></li>
                        <li class="list-inline-item"><%= link_to 'Destroy', award, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                    </ul>
                </div>
            </div>
        <% end %>
        </div>
    </div>
</section>

app/views/awards/new.html.erb
<div class="header">
    <div class="container">
        <%= link_to 'Nominate Her', awards_path %>
    </div>
</div>

<div class="page-title">
	<div class="container">
	    <h1>Submit a new award</h1>
    </div>
</div>

<div class="container">
    <%= render 'form', award: @award %>

</div>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
    <div class="container">
        <%= link_to 'Nominate Her', awards_path %>
    </div>
</div>

<div class="page-title">
	<div class="container">
	    <h1><%= @award.name %></h1>
    </div>
</div>


<div class="container">

<div class="row mb-5">
	<div class="col-sm-4">
		<h2>URL</h2>
	</div>
	<div class="col-sm-8 pt-2">
		<a href="<%= @award.link %>" target="_blank"> <%= @award.link %></a>
	</div>
</div>	

<hr class="my-5">

<div class="row mb-5">
	<div class="col-sm-4">
		<h2>Description</h2>
	</div>
	<div class="col-sm-8 pt-2">
		<%= @award.description %>
	</div>
</div>	

<hr class="my-5">

<div class="row mb-5">
	<div class="col-sm-4">
		<h2>Nomination close date</h2>
	</div>
	<div class="col-sm-8 pt-2">
		<%= @award.nomination_close_date %>
	</div>
</div>	

<hr class="my-5">


<%= link_to 'Edit Award Details', edit_award_path(@award), class: 'btn btn-primary btn-lg mb-5'  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>NominateHer</title>
    <%= csrf_meta_tags %>


<!--     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
 -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>